title: Projeto Distúrbio
email: igorafelipe@gmail.com
description: "O papel da ocorrência de distúrbios no processo de invasão biológica e manutenção da diversidade em paisagens dinâmicas \n Palavras-chave: Fragmentação. Modelo Matemático. Restauração. Metapopulação. "
baseurl: "disturbance"
url: ""
github_username: iafelipe

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
